#
# This is the config for the TOI helm installer.
# It describes the chart to be deployed together with
# the localization information (imageMapping).
#
chart:
  resource:
    name: chart

imageMapping: # the value mapping for accessing the image included in the component version
  - tag: image.tag
    repository: image.repository
    resource:
      name: image

kubeConfigName: target
release: echoserver
createNamespace: true

# default helm values can be provided here. They will override any values given in the
# configTemplate from the packagespec.yaml
values:
  replicaCount: 2
  ingress:
    enabled: false
  config:
    color: "#0000ff"